# Generated by Django 4.0.2 on 2022-02-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_fish', models.TextField()),
                ('weight', models.FloatField()),
                ('length', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('species', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
