version: '3.8'

services:
  uwsgi:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/opt/deploy/bezen
    environment:
      - DEBUG=True
      - DJANGO_TEST_SERVER=True

  celery_worker_default:
    volumes:
      - ../:/opt/deploy/bezen
